github: [metadata]
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
theme: jekyll-theme-primer
gfm_quirks: paragraph_end

title: Shaw Almex
email: shaw@almexindia.com
phone: +91-129-2258676, +91-129-2274624
fax: +91-129-2275567

exclude: ['README.markdown','/assets/cs/sass']

sass:
  sass_dir: assets/css
  style: compressed

collections:
  vulcanizing_machine:
    output: true
  industrial_rubber_press:
    output: true
  lamination_presses:
    output: true
  tools_and_accessories:
    output: true
  fusion_systems:
    output: true
